---
- name: Compute nodes configuration
  hosts: computes
  become: yes
  gather_facts: yes

  tasks:
  - name: Install chrony ntp service
    ansible.builtin.apt:
      name: chrony
      state: latest
      update_cache: yes
  - name: Deploy chrony.conf template
    ansible.builtin.template:
      src: templates/compute-chrony.conf.j2
      dest: /etc/chrony/chrony.conf
      backup: yes
    register: chrony_config
  - name: Restart chrony
    ansible.builtin.systemd:
      name: chronyd
      state: restarted
      enabled: yes
    when: chrony_config.changed
