---
- name: Controller nodes configuration
  hosts: controllers
  become: true
  gather_facts: true

  tasks:
  # Chrony
  - name: Install chrony ntp service
    ansible.builtin.apt:
      name: chrony
      state: present
      update_cache: true
  - name: Deploy chrony.conf template
    ansible.builtin.template:
      src: templates/controllers/controller-chrony.conf.j2
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: 0644
      backup: true
    notify:
      - Restart chrony
  - name: Ensure chrony is running
    ansible.builtin.systemd:
      name: chronyd
      state: started
      enabled: true

  handlers:
    - name: Restart chrony
      ansible.builtin.systemd:
        name: chronyd
        state: restarted

  roles:
    - mysql
    - rabbitmq
    - memcached
    - keystone
