---
- name: Common tasks
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Add IP address of all hosts to all hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ item }}\t{{ hostvars[item]['ansible_hostname'] }}"
        state: present
      with_items: "{{ groups['all'] }}"

  roles:
    - common

- name: Controller nodes configuration
  hosts: controllers
  become: true
  gather_facts: true

  roles:
    - ntp/server
    - mysql
    - rabbitmq
    - memcached
    - keystone
    - glance
    - placement

- name: Compute nodes configuration
  hosts: computes
  become: true
  gather_facts: true

  roles:
    - ntp/client
