---
- name: Common tasks
  hosts: all
  become: true
  gather_facts: true

  roles:
    - common

- name: Controller nodes configuration
  hosts: controllers
  become: true
  gather_facts: true

  roles:
    - ntp/server
    - mysql
    - rabbitmq
    - memcached
    - keystone

# - name: Compute nodes configuration
#   hosts: computes
#   become: true
#   gather_facts: true

#   roles:
#     - ntp/client
