---
- name: Common tasks
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Set timezone to Europe/Amsterdam
      community.general.timezone:
        name: Europe/Amsterdam

    - name: Configure sudo
      community.general.sudoers:
        name: "00-{{ local_admin_user }}-all-nopassword"
        nopassword: true
        state: present
        user: "{{ local_admin_user }}"
        commands: ALL

    - name: Disable lid close sleep
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^#HandleLidSwitch=suspend|^HandleLidSwitch=.*"
        line: "HandleLidSwitch=ignore"
      register: logind_config

    - name: Restart logind service
      ansible.builtin.systemd:
        name: systemd-logind
        state: restarted
      when: logind_config.changed

    - name: Disable useless services
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
      loop: "{{ useless_services }}"

    - name: Add IP address of all hosts to all hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
        state: present
      with_items: "{{ groups.all }}"

    - name: Remove loopback address associated with the host
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^127.0.1.1.*"
        state: absent

    - name: Install Ubuntu Cloud Keyring
      ansible.builtin.apt:
        name: ubuntu-cloud-keyring
        state: latest
        update_cache: yes
      register: keyring_installed

    - name: Cloud Archive Openstack - Ubuntu
      ansible.builtin.apt_repository:
        repo: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu {{ ansible_distribution_release }}-updates/{{ openstack_version }} main"
        state: present
      when: keyring_installed is succeeded

- import_playbook: controller.yml
- import_playbook: compute.yml
