- name: Install chrony ntp service
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true
- name: Deploy chrony.conf template
  ansible.builtin.template:
    src: compute-chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart chrony
- name: Ensure chrony is running
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true