- name: Restart nova
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy

- name: Nova API DB sync
  ansible.builtin.command: "nova-manage api_db sync"
  become: true
  become_user: nova
  become_method: sudo
  become_flags: 'su - nova -s /bin/sh -c'

- name: Nova map cell0
  ansible.builtin.command: "nova-manage cell_v2 map_cell0"
  become: true
  become_user: nova
  become_method: sudo
  become_flags: 'su - nova -s /bin/sh -c'

- name: Nova create cell1
  ansible.builtin.command: "nova-manage cell_v2 create_cell --name=cell1 --verbose"
  become: true
  become_user: nova
  become_method: sudo
  become_flags: 'su - nova -s /bin/sh -c'

- name: Nova DB sync
  ansible.builtin.command: "nova-manage db sync"
  become: true
  become_user: nova
  become_method: sudo
  become_flags: 'su - nova -s /bin/sh -c'
