# Memcached
- name: Install Memcached
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ ('present' if op == 'install') or 'latest' }}"
    update_cache: true
  loop:
    - memcached
    - python3-memcache
- name: Configure memcached
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    regexp: "^-l.*"
    line: "-l {{ hostvars[groups['controllers'][0]]['ansible_default_ipv4']['address'] }}"
  notify:
    - Restart memcached
- name: Ensure memcached is running
  ansible.builtin.systemd:
    name: memcached
    state: started
